# Module src_debug_tserver translation file for language=en
# Copyright (C) 2011 Wingware
# Wingware Python IDE -- www.wingware.com
#
msgid ""
msgstr ""
"Project-Id-Version: 4.0.1\n"
"POT-Creation-Date: 2025-01-13 08:22-0500\n"
"PO-Revision-Date: 2011-03-30 22:09 EDT\n"
"Last-Translator: Wingware <support@wingware.com>\n"
"Language-Team: None\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: text/plain\n"
"Generated-By: pygettext.py 1.5\n"

#: src/debug/tserver/dbginspect.py:59 src/debug/tserver/dbgserver.py:3278
#: src/debug/tserver/dbgutils.py:594 src/debug/tserver/dbgutils.py:620
msgid "(truncated)"
msgstr ""

#: src/debug/tserver/dbginspect.py:827 src/debug/tserver/dbginspect.py:891
#: src/debug/tserver/dbginspect.py:967 src/debug/tserver/dbginspect.py:1175
#: src/debug/tserver/dbginspect.py:1246 src/debug/tserver/dbginspect.py:1354
#: src/debug/tserver/dbgutils.py:585 src/debug/tserver/dbgutils.py:613
#: src/debug/tserver/dbgutils.py:2856
msgid " at %s"
msgstr ""

#: src/debug/tserver/dbginspect.py:832 src/debug/tserver/dbginspect.py:896
#: src/debug/tserver/dbginspect.py:1263 src/debug/tserver/dbgutils.py:242
msgid "<opaque %s%s>"
msgstr ""

#: src/debug/tserver/dbginspect.py:918
msgid "<huge %s%s; len=%s>"
msgstr ""

#: src/debug/tserver/dbginspect.py:973 src/debug/tserver/dbginspect.py:994
#: src/debug/tserver/dbgutils.py:622 src/debug/tserver/dbgutils.py:2867
#: src/debug/tserver/dbgutils.py:2872
msgid "<huge %s%s; len=%i>"
msgstr ""

#: src/debug/tserver/dbginspect.py:1194 src/debug/tserver/dbgutils.py:2874
msgid "<huge %s%s>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1478
msgid "<module>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1621
msgid "<error evaluating>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2226 src/debug/tserver/dbgserver.py:2262
msgid "<thread %i is running>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2229 src/debug/tserver/dbgserver.py:2265
msgid "<invalid thread id %s or stack index %s>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2231 src/debug/tserver/dbgserver.py:2267
msgid "<invalid stack frame>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2295 src/debug/tserver/dbgserver.py:2324
msgid "<sys.modules does not exist>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2298 src/debug/tserver/dbgserver.py:2329
msgid "<error accessing sys.modules>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2326
msgid "<no longer exists"
msgstr ""

#: src/debug/tserver/dbgserver.py:2374 src/debug/tserver/dbgserver.py:2427
msgid "<no longer exists>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2405 src/debug/tserver/dbgserver.py:4821
msgid "<parent too large>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2407 src/debug/tserver/dbgserver.py:4823
msgid "<invalid parent type>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2417 src/debug/tserver/dbgserver.py:2909
msgid "<value not found>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2897
msgid "<thread is running>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2899
msgid "<invalid context>"
msgstr ""

#: src/debug/tserver/dbgserver.py:4829
msgid "<invalid path %s at pos=%i>"
msgstr ""

#: src/debug/tserver/dbgutils.py:159
msgid "<undefined>"
msgstr ""

#: src/debug/tserver/dbgutils.py:175
msgid "at"
msgstr ""

#: src/debug/tserver/dbgutils.py:185
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:195 src/debug/tserver/dbgutils.py:2968
msgid "<error handling value>"
msgstr ""

#: src/debug/tserver/dbgutils.py:197
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:205
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:225
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:841 src/debug/tserver/dbgutils.py:853
msgid ", pos "
msgstr ""

#: src/debug/tserver/dbgutils.py:857
msgid ", line "
msgstr ""

#: src/debug/tserver/dbgutils.py:859
msgid "SyntaxError: "
msgstr ""

#: src/debug/tserver/dbgutils.py:887
msgid "Error"
msgstr ""

#: src/debug/tserver/dbgutils.py:897
msgid "Error: Wing was unable to pack up an exception message"
msgstr ""

#: src/debug/tserver/dbgutils.py:3904 src/debug/tserver/dbgutils.py:3921
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3904 src/debug/tserver/dbgutils.py:3921
msgid "Value"
msgstr ""

#: src/debug/tserver/dbgutils.py:3916 src/debug/tserver/dbgutils.py:3943
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:466
msgid "Redirected I/O failed on closed debug connection"
msgstr ""

#: src/debug/tserver/netserver.py:629
msgid "EOF when reading a line"
msgstr ""

#: src/debug/tserver/netserver.py:1207
msgid "(unavailable)"
msgstr ""

#: src/debug/tserver/netserver.py:1480
msgid "[omitting some output]"
msgstr ""

#: src/debug/tserver/startdebug.py:244 src/debug/tserver/startdebug.py:376
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr ""

#: src/debug/tserver/startdebug.py:248 src/debug/tserver/startdebug.py:380
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr ""

#: src/debug/tserver/startdebug.py:426
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:427
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:428
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:442
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:458
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:469 src/debug/tserver/startdebug.py:494
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:683
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:684
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:685
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:771 src/debug/tserver/startdebug.py:773
msgid "-- Type return or enter to exit --\n"
msgstr ""
